### PR TITLE
Pass title prop to input

### LINKED ISSUE #104: Prop "title" is ignored
If I pass the `title` as a prop to the `Checkbox` component, it will be removed before passing it to the HTML attribute `title`.
Like the `data-*`, `aria-*` and `role` attributes it should be passed over to the HTML.

E.g.
`<Checkbox title="Dr. Prof." />`
should be mapped to
`<input type="checkbox" title="Dr. Prof." />`.

### PR DESCRIPTION
**Pull request by kilya11**
Resolves #104

### CODE REVIEW

**Comment by xinpingwang** [comment]
@yiminghe @afc163 any one can help merge this pr. and release a new version, or give some suggestion? seems this pr solve the problem fine.

**Comment by afc163** [comment]
图片

**Comment by xinpingwang** [comment]
@kilya11 will you solve the git conflicts, or I can make a pr base on your commit.

**Comment by xinpingwang** [comment]
@afc163 I create a new pull request #218, which solved the conflict. 😀

**Pull request closed without merging**
